[package]
name = "krusty_grab"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
eframe = "0.22.0"
egui = "0.22.0"
egui_extras = "0.22.0"
image = "0.24.6"
screenshots = "0.7.1"
